security:
  basic:
    users:
      - username: admin
        password: adminpass
        role: ADMIN
      - username: user
        password: userpass
        role: USER

server:
  tomcat:
    threads:
      max: 50
      min-spare: 10
